Repository beethub/environment-beet-k8s-1-staging, pull requests merged in 2020-03, with the labels that each got.

#1 chore: receipt-api to 0.0.4
  env/Chart.yaml
  env/requirements.yaml
Labels: size/S, updatebot

#2 chore: receipt-api to 0.0.5
  env/requirements.yaml
Labels: size/XS, updatebot

#3 chore: receipt-api to 0.0.7
  env/requirements.yaml
Labels: size/XS, updatebot

#4 Remove Naspace for the urlTemplate
  env/values.yaml
Labels: size/XS

#5 chore: receipt-api to 0.0.8
  env/requirements.yaml
Labels: size/XS, updatebot

#6 chore: receipt-api to 0.0.9
  env/requirements.yaml
Labels: size/XS, updatebot

#7 chore: receipt-api to 0.0.13
  env/requirements.yaml
Labels: size/XS, updatebot

#8 chore: receipt-api to 0.0.14
  env/requirements.yaml
Labels: size/XS, updatebot

#9 chore: receipt-api to 0.0.15
  env/requirements.yaml
Labels: size/XS, updatebot

#10 chore: receipt-api to 0.0.16
  env/requirements.yaml
Labels: size/XS, updatebot

#11 chore: receipt-api to 0.0.17
  env/requirements.yaml
Labels: size/XS, updatebot
